Allow pickle as an input to the simulator
menu-hanke/sim-workbench pull request #111
Opened 2022-06-29 12:03 UTC by unie31

closing #99

2022-06-29 12:20 UTC, dmela commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
I'd say this doesn't need to be a function. Could be just a oneliner in the code.. what does @jpy-luke think?

2022-06-29 12:26 UTC, dmela approved these changes
Looks great, one comment for you to consider.

2022-06-29 12:57 UTC, jpy-luke commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
I would rather you add a command line parameter
-i, --input-type
with default to pickle.

Don't try to determine type from file ending.

2022-06-29 13:01 UTC, dmela commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
Ok, now I am curious. Why do you @jpy-luke see this as best way to go?

2022-06-30 06:28 UTC, jpy-luke commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
1) To stay consistent with the behaviour with vmi-data-converter.
2) Filename suffix is not trustworthy metadata.
3) Let the user be responsible of knowing what format they are supplying.

2022-06-30 06:28 UTC, jpy-luke requested changes
Change format selection as requested

2022-06-30 07:46 UTC, dmela commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
Valid stuff. Thanks.

2022-06-30 08:20 UTC, unie31 commented on app/file_io.py
> +    fmt = resolve_file_format(file_path)
added command line parameter --input_format, since that's the name of the corresponding parameter in vmi-data-converter.

2022-06-30 12:41 UTC, jpy-luke commented on app/app_io.py
> +    parser.add_argument('-i','--input_format',
--input-format

2022-06-30 12:44 UTC, jpy-luke commented on app/app_io.py
> +    parser.add_argument('-i','--input_format',
Also add the choices here, like in vmi-data-converter:
choices=['pickle', 'json']

then the parser probably knows to abort if something else is offered

2022-06-30 12:46 UTC, jpy-luke requested changes
2 changes

2022-07-04 07:07 UTC, jpy-luke approved these changes

2022-07-04 07:10 UTC, merged