Thinning table from file param
menu-hanke/sim-workbench pull request #123
Opened 2022-07-26 10:22 UTC by unie31

closing #49 

If a thinning limit file is provided in control.yaml, then the thinning operations (excluding first_thinning) will use the limits from the file instead of the hardcoded structure (although for now the hardcoded structure and the limits fileare identical)

2022-07-26 10:33 UTC, unie31 commented on forestry/thinning_limits.py
> +    SOUTHERN_FINLAND = 'southern_finland'
Added this value, as the [Thin.txt](https://github.com/menu-hanke/additional-content/blob/main/sim12/Thin.txt) specifies that the limits apply to Southern Finland, not Eastern Finland. However, for now I haven't used SOUTHERN_FINLAND in the code, e.g. the hardcoded structure uses Eastern Finland:

https://github.com/menu-hanke/sim-workbench/blob/fe4c14f19ab6ceccbcc339b2c43bdae518917c69/forestry/thinning_limits.py#L40

2022-07-26 10:33 UTC, unie31 commented on forestry/thinning_limits.py
> +    return limits_for_species
For now this logic relies on strict assumptions: the thinning limits file needs to have 9 columns and 64 rows and that the rows are in the order defined in [Thin.txt](https://github.com/menu-hanke/additional-content/blob/main/sim12/Thin.txt). Would be useful to understand whether the source file needs to be in the rather vague format, or could the user give a CSV with headers, which could be more transparent and less error prone.

2022-08-03 08:17 UTC, dmela commented on forestry/thinning_limits.py
> +    return limits_for_species
I agree with the readability aspect of the Thin.txt file.

CSV is a good idea. We would only need to add few extra columns (site type, peatland category and species) for each row.

Than there is possibility to convert the Thin.txt file format into json as json->dict conversion is trivial and we would not have to refactor the old functions if we structure the json in respect to present `THINNING_LIMITS` dict.

But lets wait for @jpy-luke, becuase he might have a other option.

2022-08-08 06:44 UTC, jpy-luke commented on forestry/thinning_limits.py
> +    return limits_for_species
Foundational idea is to be able to support parameter files such as these as they are in old Mela. Of course it would be nice to see improvement with this. But let that be another task and based on a design decision together with the domain experts.

2022-08-18 11:10 UTC, dmela commented on forestry/thinning_limits.py
> +def create_thinning_limits_table(input_data: str, countyKey: CountyKey = CountyKey.EASTERN_FINLAND) -> Dict:
Output type is List

2022-08-18 11:11 UTC, dmela commented on forestry/thinning_limits.py
> +def create_thinning_limits_table(input_data: str, countyKey: CountyKey = CountyKey.EASTERN_FINLAND) -> Dict:
In fact check the whole signature there is something odd in it.

2022-08-18 11:25 UTC, dmela commented on forestry/thinning_limits.py
> +    If file not provided in control.yaml, the hardcoded THINNING_LIMITS structure will be used."""
Could be god idea to mention that the `thinning limits` parameter is optional so it makes the hardcoded structure a default case (for now). We need to open up this again task again in some point of time and make it more robust from the file format perspective.

2022-08-18 11:27 UTC, dmela commented on forestry/thinning_limits.py
> +def create_thinning_limits_table(input_data: str, countyKey: CountyKey = CountyKey.EASTERN_FINLAND) -> Dict:
Check if the import typing Dict is necessary after changing the output type in the signature

2022-08-18 11:32 UTC, dmela requested changes
Thanks, looking good. Left few comments. Also what I noticed also was that there are no test suites for the new thinning limits utility functions `create_thinning_limits_table` and `get_thinning_limits_from_parameter_file_contents` is there a spesific reason for this?

Because if we see this as temporary solution. I just could give it a approvement that we do not fix the tests.

2022-08-24 11:38 UTC, merged