Master test for simulator and post-processing
menu-hanke/sim-workbench pull request #124
Opened 2022-07-27 09:34 UTC by unie31

Closing #119

2022-07-27 09:38 UTC, unie31 commented on tests/sim/main_test.py
> +                self.assertTrue(True)
I assume this kind of "heuristic" assertion is enough, or should the simulator be made to return a value on successful completion?

2022-08-02 11:51 UTC, dmela commented on tests/sim/main_test.py
> +                self.assertTrue(True)
I would probably tests if the file exists... i.e. if the runtime was able to produce the output.
But in this case it is more a matter of taste. I would say it is up to you.

2022-08-02 11:51 UTC, dmela commented on tests/sim/main_test.py
> +        NOTE: it uses the control.yaml in the root of the project to easily test the most recent version of it."""
I would move this and the postp_processing docstring as module docstring. They are so similar...

2022-08-02 11:59 UTC, dmela commented on app/app_io.py
> +def function_arguments_to_argparse_namespace(args: dict):
Missing signature output type. I assume it is argparse.Namespace?

2022-08-02 12:00 UTC, dmela commented on app/app_io.py
> +def function_arguments_to_argparse_namespace(args: dict):
or SimpleNamespace?

2022-08-02 12:07 UTC, dmela commented on app/post_processing.py
> +    """:test_automation_arguments: are only passed in from a test that ensures the post processing main remains runnable after feature changes."""
I would like to say this comment is not necessary. I think the variable name already holds enough detail for the reader to understand that `test_automation_arguments` are for testing.

I could imagine that eventually such a docstring will start to rot. Purpose of a docstring is to describe what the function does, so I would add a more detailed description about what is the purpose of the main function or then remove the whole line.

2022-08-02 12:10 UTC, dmela commented on app/app_io.py
> +def function_arguments_to_argparse_namespace(args: dict):
Also would consider renaming the function to e.g. test_arguments etc.

2022-08-02 12:17 UTC, dmela commented on app/post_processing.py
> +        app_arguments = post_processing_cli_arguments(sys.argv[1:])
Could we write this as a onelier?
```
app_arguments = post_processing_cli_arguments(sys.argv[1:]) if test_automaton_arguments is None else function_arguments_to_argparse_namespace(test_automation_arguments)
```

2022-08-02 12:18 UTC, dmela requested changes
Looking good. Lefts few improvement ideas for you to consider.

2022-08-09 08:21 UTC, unie31 commented on app/post_processing.py
> +        app_arguments = post_processing_cli_arguments(sys.argv[1:])
I'd say that is less pleasant to read

2022-08-10 06:39 UTC, dmela commented
Try to refactor the solution to use `sys.argv` so that the `app` library would not be dependent from the `tests` library. In order to do this drop the `test_arguments_to_argparse_namespace` and refactor the test suites so that `sys.argv` would be inflated before calling the `main` function. If this is possible you can use functions in `app.app_io` module to read the "CLI" arguments.

2022-08-16 08:14 UTC, dmela approved these changes
Great work!

2022-08-18 11:34 UTC, merged