First grow model
menu-hanke/sim-workbench pull request #18
Opened 2022-03-10 14:17 UTC by dmela

First actual grow model from the forestry domain.
(ported from reposotory MENU/additionl-content // sim12.c file)

The grow model updates breast height diameter and height of the tree.
The logic is as follows:
* calcualte stadn level aggregate values total basal area and dominant height
* generate species spesific lists of reference trees
* go through all trees of same species and calculate tree species spesific aggregate values:
  * breast_height_aggregate
  * height_aggregate
  * age_aggreagate
* After these prerequisitions have been done we can calculate with the actual models for each tree and update the tree variables breast height diameter and height of the tree.

Also includes the forestry utility functions that are generic implementations which may be used to calculate stand level aggregate values. Also tree species spesific aggregate values may be calculated (eg. breast heigh diameter weighted with total basal area of tree species x).

Notice that this is a quick and dirty implementation with additional forestry utility functions. So approvement suggestions are welcome.

2022-03-11 08:17 UTC, artohaa commented
This is a good start!
On thing I noticed: Diameter of the tree can be 0, thus calculate_basal_area -function should be prepared for that 
(e.g. try...  except return 0.0).

2022-03-14 03:10 UTC, jpy-luke commented on forestry/forestry_utils.py
> +    return total
This could be simplified as
return sum(map(f, reference_trees))

2022-03-14 03:16 UTC, jpy-luke commented on forestry/forestry_utils.py
> +def calculate_attribute_aggregate(reference_trees: List[ReferenceTree], f: Callable) -> float:
Maybe the name calculate_attribute_aggregate should be changed to reflect the fact that basal_area_total is a key element for the computation. Sounds too generic for such specific purpose. Add a little docstring to describe what to expect from this function, especially what kind of function f should be.

2022-03-14 03:20 UTC, jpy-luke commented on forestry/forestry_utils.py
> +    return trees_by_species
I don't get this function. The name is says filter but the result is a grouping of trees into separate lists by species. Explain it to me in a call please.

2022-03-14 03:22 UTC, jpy-luke commented on forestry/forestry_utils.py
> +    return math.pi * math.pow(tree.breast_height_diameter / 200, 2) * tree.stems_per_ha
Add docstring to refer to the source of this formula.

2022-03-14 03:33 UTC, jpy-luke commented on forestry/operations.py
> +            compound_interest = math.pow(compound_interest, 5)
Please move computing the compound_interest to a separate function. And let's call it compounded_growth_factor. compound_interest is a strictly financial term, I think.

2022-03-14 03:38 UTC, jpy-luke commented on forestry/operations.py
> +                growth_percent_height = math.exp(5.4636-0.9002*math.log(biological_age_aggregate)+0.5475*math.log(d13_aggregate)-1.1339*math.log(tree.height))
I would like to see two separate functions here. One for yearly diameter growth by species, other for yearly height growth by species. This way the if-else here is unnecessary and the functions can be tested independently.

2022-03-14 03:43 UTC, jpy-luke commented on forestry/operations.py
> +                lambda tree: tree.__getattribute__('breast_height_diameter') * f_util.calculate_basal_area(tree)
Why __getattribute__? Should certainly not be necessary.

2022-03-14 03:56 UTC, jpy-luke requested changes
Feedback and change requests in separate comments. Let's talk about this generally on a call.

2022-03-14 12:54 UTC, dmela commented on forestry/forestry_utils.py
> +    return total
done

2022-03-15 09:49 UTC, dmela commented on forestry/forestry_utils.py
> +    return trees_by_species
done

2022-03-15 09:53 UTC, dmela commented on forestry/forestry_utils.py
> +    return math.pi * math.pow(tree.breast_height_diameter / 200, 2) * tree.stems_per_ha
done

2022-03-15 10:22 UTC, dmela commented on forestry/operations.py
> +            compound_interest = math.pow(compound_interest, 5)
Done

2022-03-18 11:50 UTC, dmela commented on forestry/operations.py
> +                growth_percent_height = math.exp(5.4636-0.9002*math.log(biological_age_aggregate)+0.5475*math.log(d13_aggregate)-1.1339*math.log(tree.height))
done

2022-03-18 11:57 UTC, dmela commented on forestry/operations.py
> +                lambda tree: tree.__getattribute__('breast_height_diameter') * f_util.calculate_basal_area(tree)
Done

2022-03-18 12:34 UTC, dmela commented on forestry/forestry_utils.py
> +def calculate_attribute_aggregate(reference_trees: List[ReferenceTree], f: Callable) -> float:
done

2022-03-18 12:35 UTC, dmela commented
When through the comments and committed changes. Re-requested approval.

2022-03-21 06:20 UTC, jpy-luke commented on forestry/forestry_utils.py
> +        return math.pi * math.pow(tree.breast_height_diameter / radius_m, 2) * tree.stems_per_ha
Ok so the formula is for `area = pi * r^2`. Which is of course `pi * (d/2)^2`. We know for a fact that `tree.breast_height_diameter` is actually in centimetres, not metres. So the docstring is wrong, and the code definitely has an ugly construct to coerce the result into metres. Definitely the constant should not be called `radius_m`, since we are actually talking about the factor that converts diameter to radius. So here's what I suggest: make a variable for the converted radius of the tree in metres and just use that as a parameter for the pow function.

2022-03-21 06:32 UTC, jpy-luke commented on tests/forestry/forestry_utils_test.py
> +            self.assertEquals(i[1], round(result, 3))
Make this test class inherit test_util.ConverterTestSuite so you can use the run_with_test_assertions tool, like has become common in the tests of this project. Also you need to make the input arguments as list instead of tuple for that.

2022-03-21 06:38 UTC, jpy-luke requested changes
Good progress. Two more change requests in comments.

2022-03-21 09:28 UTC, jpy-luke commented on forestry/forestry_utils.py
> +        return math.pi * math.pow(tree.breast_height_diameter / radius_m, 2) * tree.stems_per_ha
Another very odd thing that I just thought about. The area is multiplied by stems per hectare (100m^2), while the area is in m^2. Maybe this whole formula should be verified by expert.

2022-03-21 10:20 UTC, dmela commented on tests/forestry/forestry_utils_test.py
> +            self.assertEquals(i[1], round(result, 3))
In fact the project does not include such class to inherit. It is in https://github.com/menu-hanke/vmi-data-converter.
Altough we might bring it here in some point in the future. Should it be now than?

2022-03-21 10:28 UTC, jpy-luke commented on tests/forestry/forestry_utils_test.py
> +            self.assertEquals(i[1], round(result, 3))
Oh you're right. My bad. Let's forget this for now.

2022-03-22 06:57 UTC, jpy-luke approved these changes

2022-03-22 07:02 UTC, merged