Add preprocessing step (new PR)
menu-hanke/sim-workbench pull request #54
Opened 2022-06-10 10:31 UTC by unie31

2022-06-10 10:48 UTC, jpy-luke commented on .gitignore
> +*.pickle
Let's not ignore *.pickle. If the output.pickle bothers you then write it elsewhere like ../output.pickle

2022-06-10 10:49 UTC, jpy-luke commented on app/simulator.py
> +    stands = preprocess_stands(stands, simulation_declaration)
Move this to under the strategy resolution. This step is useless if strategy resolution fails.

2022-06-10 10:51 UTC, jpy-luke commented on forestry/preprocessing.py
> +        #is there benefit from using filter here since it returns a generator which should be read from straight away?
Don't leave comments like this. And the answer is yes - filtering is easy with one-liner lambda functions. Even with the annoying explicit list conversion.

2022-06-10 10:59 UTC, jpy-luke commented on tests/forestry/preprocessing_test.py
> +        stand_is_empty = is_empty_stand_list[i]
The is_empty_stand_list thing seems like an overcomplicated and hard to read solution for this. How about just
`stand_is_empty = i <= empty_stand_count` and the same for the sapling tree thing?

2022-06-10 11:01 UTC, jpy-luke commented on tests/forestry/preprocessing_test.py
> +        excluded = preprocessing.exclude_sapling_trees(stands) #do not pass kwargs
do not pass kwargs?
It is in no way clear if this is a warning, a statement, or what? Maybe we know only from some other context?
It becomes a noisy comment only causing confusion instead of being helpful. Avoid such please.

2022-06-10 11:02 UTC, jpy-luke requested changes
Some new feedback in comments.

2022-06-13 05:12 UTC, jpy-luke approved these changes

2022-06-13 06:06 UTC, dmela commented on control.yaml
> +    hello: "world"
I could consider these to be real world examples and not something that looks like a tests case.

2022-06-13 06:07 UTC, dmela requested changes
One comment

2022-06-13 06:49 UTC, dmela approved these changes

2022-06-13 06:55 UTC, merged